### ISSUE TITLE
Need testing for location feature on devices like Samsung, OnePlus etc 

### ISSUE THREAD

**Issue by adityasonel** [solocoinapp/solocoin-android#117]
MarkYourLocation activity seems to working on devices like MI and RealMe, but there is some issue in getting location on devices like samsung and oneplus. Also there is no GPS dialog is showing on this company devices respectively, while working perfectly on MI devices.

This feature need to be tested on this android company devices.

**Comment by arbob** [comment]
I have tested it on my Oneplus. The last build you sent. It was working fine.
