### ISSUE TITLE
Scratch cards

### ISSUE THREAD

**Issue by arbob** [solocoinapp/solocoin-android#164]

**Comment by arbob** [comment]
Get to know how to implement leaderboards and scratch cards from Mishaal from iOS

scratch cards are basically hidden rewards until user opens it
and we send them using notification and it has expiry

https://docs.google.com/document/d/191QtN4He4Z3i6apTddNpHBBGOE3qBwKKU-W7ESBdeZs/edit#heading=h.n9tkatxweyk7

**Comment by aayu24** [comment]
Waiting for backend to complete API for this.
