### ISSUE TITLE
Permission scree fixes

### ISSUE THREAD

**Issue by prasadpilla** [solocoinapp/solocoin-android#64]
1.  Make location button "un-clickable" once the has set the location
2. Make the button "active" once the user marks the location and comes back to permissions screen

**Comment by kenchoong** [comment]
I have a question
"the user has set the location" 1 situation
"the user marks the location and comes back to permissions screen" - 2nd situation
this 2 situation have what difference? @apats24 @Prasad Pilla

is it mean that,
- if the user is added the location before,then make the locationButton unclickable
- if it just mark the Location now,then I make it still active,so the user can change the location again

**Comment by prasadpilla** [comment]
@kenchoong yes that's correct. 

And by active i mean make the colour gray and have the ticker

**Comment by kenchoong** [comment]
@prasadpilla so if the the user finish mark his location and comeback to the `PermissionActivity` ,the `locationButton` will be grey and a ticker..But in this moment is `locationButton` still clickable?

**Comment by prasadpilla** [comment]
@kenchoong yes that's correct

**Comment by prasadpilla** [comment]
Also @kenchoong  We shouldn't make "Continue" until all tasks are done. I.e location set for now, both earlier set and now set should work
